github.com:
    users:
        JaINTP:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: JaINTP
